#!/bin/bash

set -e
yarn workspace @rt/widget-medals build

yarn workspace @rt/widget-medals test

if [ "$CI" = "true" ]; then
  yarn workspace @rt/test-integration run serve-and-test:ci
else
  yarn workspace @rt/test-integration run serve-and-test
fi